Repository CycloneDX/cyclonedx-node-npm, pull requests merged in 2022-09, with the labels that each got.

#105 docs: explain call for local install and usage better
  HISTORY.md
  README.md
Labels: documentation

#91 Fix failing to run when launched with npx
  HISTORY.md
  README.md
  package.json
  src/builders.ts
Labels: enhancement

#106 chode(deps): bump dependencies
  .eslintrc.js
  package-lock.json
  package.json
  src/builders.ts
  tests/_data/npm-ls_demo-results/index.js
  tests/_helper/index.js
  tests/integration/synthetics/cli.run.test.js
Labels: dependencies

#107 feat: add CLI switch `--ignore-npm-errors` to ignore/suppress NPM errors
  HISTORY.md
  README.md
  src/builders.ts
  src/cli.ts
  tests/_data/npm-ls_demo-results/npm-ls_replacement.js
  tests/integration/synthetics/cli.run.test.js
Labels: enhancement

#111 QA: eslint plugins
  .eslintrc.js
  HISTORY.md
  package-lock.json
  package.json
  src/builders.ts
  src/cli.ts
Labels: dependencies, QA

#123 Demo example results
  .editorconfig
  HISTORY.md
  README.md
  demo/README.md
  demo/bundled-dependencies/README.md
  demo/bundled-dependencies/example-results/bom.1.2.json
  demo/bundled-dependencies/example-results/bom.1.2.xml
  demo/bundled-dependencies/example-results/bom.1.3.json
  demo/bundled-dependencies/example-results/bom.1.3.xml
  demo/bundled-dependencies/example-results/bom.1.4.json
  demo/bundled-dependencies/example-results/bom.1.4.xml
  demo/dev-dependencies/README.md
  demo/dev-dependencies/example-results/bom.1.2.json
  demo/dev-dependencies/example-results/bom.1.2.xml
  demo/dev-dependencies/example-results/bom.1.3.json
  demo/dev-dependencies/example-results/bom.1.3.xml
  demo/dev-dependencies/example-results/bom.1.4.json
  demo/dev-dependencies/example-results/bom.1.4.xml
  demo/gen-boms.sh
  demo/juice-shop/example-results/bom.1.2.json
  demo/juice-shop/example-results/bom.1.2.xml
  demo/juice-shop/example-results/bom.1.3.json
  demo/juice-shop/example-results/bom.1.3.xml
  demo/juice-shop/example-results/bom.1.4.json
  demo/juice-shop/example-results/bom.1.4.xml
  demo/local-dependencies/example-results/bom.1.2.json
  demo/local-dependencies/example-results/bom.1.2.xml
  demo/local-dependencies/example-results/bom.1.3.json
  demo/local-dependencies/example-results/bom.1.3.xml
  demo/local-dependencies/example-results/bom.1.4.json
  demo/local-dependencies/example-results/bom.1.4.xml
  demo/local-workspaces/README.md
  demo/local-workspaces/example-results/bom.1.2.json
  demo/local-workspaces/example-results/bom.1.2.xml
  demo/local-workspaces/example-results/bom.1.3.json
  demo/local-workspaces/example-results/bom.1.3.xml
  demo/local-workspaces/example-results/bom.1.4.json
  demo/local-workspaces/example-results/bom.1.4.xml
Labels: documentation
