Repository CycloneDX/cyclonedx-node-npm, pull requests merged in 2023-04, with the labels that each got.

#647 docs: document how to change npm executable
  HISTORY.md
  README.md
Labels: documentation

#668 chore: disable `jest`'s injectGlobals
  jest.config.js
Labels: chore

#675 ci: use node20
  .github/workflows/nodejs.yml
  .github/workflows/npm-ls_demo-results.yml
  .github/workflows/release.yml
  package.json
Labels: CI
